version: '3'

services:
  db:
    image: postgres:15
    restart: always
    container_name: db-tests-nikke
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tests