name: Test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    environment: Test
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Docker up and migration
        run: npm run docker:test:ci

      - name: Init unit tests and integration
        run: npm run test:ci
    
